### ISSUE TITLE
como configuro pelo arquivo klc?

### ISSUE THREAD

**Issue by renatolobojr** [nandoflorestan/teclado-br#12]
alguém pra explicar como edita o arquivo

**Comment by nandoflorestan** [comment]
Os drivers para Windows têm seu código-fonte nos arquivos de extensão .klc.  Esse formato de arquivo é de um utilitário chamado Microsoft Keyboard Layout Creator, o programa que deve ser utilizado para editá-los.  Ao final do processo o programa gera instaladores .msi.
