### ISSUE TITLE
Apple Macintosh

### ISSUE THREAD

**Issue by nandoflorestan** [nandoflorestan/teclado-br#4]
Não existe versão de nenhum dos 3 layouts para Mac...

Acredito que no caso do Mac seja cabível criar um projeto separado, para o qual eu linkaria com o maior prazer.

**Comment by LordNigel** [comment]
Olá a todos. Sou novato em GitHub então não sei como proceder aqui.
Quis provar o BR Nativo, mas na ausência de um layout para Mac, fiz um do zero no Ukelele e agora testei e está ok. Fiz ele para meu uso, incluindo alguns caracteres de esperanto usando dead keys e deixando apenas alguns simbolos mais uteis para mim usando Alt, etc. Gostaria de imitar o esquema do layout Dvorak-Qwerty do Mac, no qual o pressionar da tecla Command volta para querty para o uso de atalhos como Copiar, Colar, etc. Porém, ainda precisarei aprender a fazer isso.
Há interesse no arquivo do bundle? É só colar na pasta de KeyboardLayouts na Biblioteca e pronto.
Como faço para incluir no projeto?

**Comment by LordNigel** [comment]
Fiz um fork e nele coloquei o Bundle para quem quiser testar. Agradeço mais dicas do que devo fazer para fazer os procedimentos direitinho.

**Comment by nandoflorestan** [comment]
Estou fechando este ticket porque agora o projeto contém o Dvorak e o Nativo para Macintosh.
