### ISSUE TITLE
Ilustração do AltGr

### ISSUE THREAD

**Issue by diogoko** [nandoflorestan/teclado-br#8]
Criei uma ilustração, baseada nas imagens do Heitor Moraes, com os caracteres que são digitados ao segurar a tecla AltGr no br-dvorak (Windows). Talvez possa ser útil para mais alguém.

![br-dvorak-altgr](https://f.cloud.github.com/assets/1585594/1709716/4b1cd0d6-6123-11e3-9e04-62b089bc0851.png)

**Comment by nandoflorestan** [comment]
Obrigado.  Após reorganizar os arquivos neste repositório foi possível colocar essa ilustração na pasta do brdk para Windows e exibi-la no README respectivo.
